FROM gcc:latest

WORKDIR /home/

CMD ["/bin/bash"]

# docker build -t gcc .
# docker run -it --rm -v ${PWD}:/home/ gcc

# gcc -o main -lpthread -std=c99 main.c && ./main
# gcc -o main -lpthread -std=gnu99 main.c && ./main